config/routes.rb
Rails.application.routes.draw do
  resources :places do
    resources :comments
  end

  get '/places/comments/:id' => 'comments#like'

  root "places#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :place
end

app/models/place.rb
class Place < ActiveRecord::Base
	validates :name, :location, :description, presence: true
	validates :rating, numericality: {in: [1,2,3,4,5]}

	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @place = Place.find(params[:place_id])
    @comment = @place.comments.create(comment_params)
    redirect_to place_path(@place)
  end

  def like
  	@comment = Comment.find(params[:id])

  	@comment.likes += 1

  	@place = Place.find(params[:place_id])

  	redirect_to '/places'
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :text, :reference)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	def index
		@places = Place.all
	end

	def show
		@place = Place.find(params[:id])
	end

	def new
		@place = Place.new
	end

	def create
		@place = Place.new(place_params)

		if @place.save
			redirect_to place_path(@place)
		else
			render :new
		end
	end

	def edit
		@place = Place.find(params[:id])
	end

	def update
		@place = Place.find(params[:id])

		if @place.update(place_params)
			redirect_to place_path(@place)
		else
			render :edit
		end
	end

	def destroy
		@place = Place.find(params[:id])
		@place.destroy

		redirect_to places_path
	end

private
	def place_params
		params.require(:place).permit(:name, :location, :rating, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LekkerPlekke</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/places/_form.html.erb
<% if @place.errors.present? %>
	<% @place.errors.full_messages.each do |msg| %>
		<p><%= msg %></p>
	<% end %>
<% end%>

<%= form_for @place do |f| %>
<p>
	<%= f.label :name %><br>
	<%= f.text_field :name %>
</p>
<p>
	<%= f.label :location %><br>
	<%= f.text_field :location %>
</p>
<p>
	<%= f.label :rating%><br>
	<%= f.select :rating, ['Select a rating',1, 2, 3, 4, 5]%>
</p>
<p>
	<%= f.label :description %><br>
	<%= f.text_field :description %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/places/edit.html.erb
<h1>Editing the place!</h1>

<%= render 'form' %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<%= link_to 'New place', new_place_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Rating</th>
    <th>Description</th>
  </tr>
 
  <% @places.each do |place| %>
    <tr>
      <td><%= place.name %></td>
      <td><%= place.location %></td>
      <td><%= place.rating %></td>
      <td><%= place.description%></td>
      <td><%= link_to 'Show', place_path(place) %></td>
      <td><%= link_to 'Edit', edit_place_path(place) %></td>
      <td><%= link_to 'Destroy', place_path(place),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/places/new.html.erb
<h1>Creating a new place!!!!!</h1>

<p>Fill out this form to create a cool new place for our app.</p>

<%= render 'form' %>

app/views/places/show.html.erb
<h1><%= @place.name%> page</h1>

<h2><%= @place.location%></h2>

<p>Rating: <%= @place.rating %></p>

<p>Description: <%= @place.description %></p>

<h2>Comments</h2>
<% @place.comments.each do |comment| %>
	<p>
		<strong>Commenter:</strong>
		<%= comment.commenter %>
	</p>
	<p>
		<strong>Text:</strong>
		<%= comment.text %>
	</p>
	<p>
		<strong>Likes:</strong>
		<%= comment.likes %>
	</p>
	<p>
		<%= link_to "Like", '/places/comments/', id: comment.id %>
	</p>
<% end %>

<h2>Add a comment</h2>

<%= form_for ([@place, @place.comments.build]) do |f| %>
	<p>
		<%= f.label :commenter %><br>
		<%= f.text_field :commenter %>
	</p>
	<p>
		<%= f.label :text %><br>
		<%= f.text_field :text %>
	</p>
	<p>
		<%= f.submit %><br>
	</p>
<% end %>

<p><%= link_to "Place List", places_path %></p>
 
<p><%= link_to "Edit", edit_place_path(@place) %></p>